services:
  - type: web
    name: paramastra-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
